### ISSUE TITLE
Add a histogram fold

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly-statistics#23]
Add a simple streaming histogram fold using a predetermined range/bins.

```
-- histogram maxBins binSize alignment
-- maxBins limits the memory, bins start at an integral multiple of alignment
-- The resulting Map consists of the (lower bound of the bin, count of items in the bin).
histogram :: Int -> a -> a -> Fold m a (Map a b)
```

Reference:

* https://github.com/composewell/streamly-examples/blob/a0ca2b38bd2df87883f3ff8054a8c5c4d4002e82/examples/Intro.hs#L101
* https://hackage.haskell.org/package/statistics-0.16.0.1/docs/Statistics-Sample-Histogram.html

**Comment by harendra-kumar** [comment]
A function that classifies the input into bins should be good enough. We can then combine it with classify folds to get a histogram. Something like:

```
-- unboundedBins binSize alignment
-- The first element of the tuple is the bin key which is the lowest integral value in the bin.
unboundedBins :: Int -> Int -> a -> (a, a)

-- boundedBins lower, size, count
-- The first element of the tuple is the bin key which is the lowest integral value in the bin.
-- Values below the lower range and above the upper range can be placed in an "unclassified" bin
boundedBins :: Int -> Int -> a -> (a, a)
```

**Comment by rnjtranjan** [comment]
fixed by https://github.com/composewell/streamly-statistics/pull/48
