### ISSUE TITLE
Add jackknife mean, variance and stddev

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly-statistics#26]
To compute jackknife mean, given an array of data e.g. `[1,2,3,4]`,  compute the sum of the elements i.e. 10 in this case. Then use `zipWith (-) (repeat 10) [1,2,3,4]` to get sums omitting one element each time, then divide the output stream by `(length [1,2,3,4] - 1)` i.e. 3. This will give a stream of mean each of which has omitted one element.

Use the same methodology to compute variance and stddev. We already have incremental computations of these in the library use that to implement jackknife versions.

**Comment by rnjtranjan** [comment]
Fixed by:
https://github.com/composewell/streamly-statistics/pull/43
https://github.com/composewell/streamly-statistics/pull/44
