### ISSUE TITLE
Add countDistinct/frequency/mode routines

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly-statistics#27]
See [this example](https://github.com/composewell/streamly-examples/blob/a0ca2b38bd2df87883f3ff8054a8c5c4d4002e82/examples/WordFrequency.hs) for a word frequency counting program.

**Comment by harendra-kumar** [comment]
We have `countDistinct` [in streamly now](https://github.com/composewell/streamly/blob/a849812d9960d5b7868e770156ab774ee8f70157/core/src/Streamly/Internal/Data/Fold.hs#L629) so we do not need that here.

**Comment by harendra-kumar** [comment]
Frequency can be implemented as:

```
frequency :: Fold m a (Map a Int)
frequency = classifyWith id Fold.length
```

And mode would be the max in the frequency map:

```
mode :: Fold m a (a, Int)
```

**Comment by rnjtranjan** [comment]
Fixed by:https://github.com/composewell/streamly-statistics/pull/46
