### ISSUE TITLE
kurtosis computation seems to be incorrect

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly-statistics#31]
As per my calculations the fourth central moment comes out to be: 𝜇4=3𝜇^4+6𝜇^2𝜎^2−4𝜇𝜇′_3+𝜇′_4 . See the haddock docs of kurtosis, I have added the computations there. But the computation in the code is different than this. Am I missing something? We need to test and fix it.

cc @adithyaov

**Comment by rnjtranjan** [comment]
fix by https://github.com/composewell/streamly-statistics/pull/42
